### ISSUE TITLE
options-conditionals

### ISSUE THREAD

**Issue by dimoooooooon** [jonathanepollack/gulp-minify-html#17] opened 2015-02-02 23:50 UTC
In the v.0.1.8 with conditionals:true it leaves both regular and IE comments.
In the v.0.1.7 with conditionals:true it left only IE comments. Which was more logical.

**Comment by jonathanepollack** [comment] 2015-02-19 14:59
Was this something we did -- or a part of Minimize?

**Comment by jonathanepollack** [comment] 2015-02-19 15:02
Also, did we ever have v0.1.8 -- because I can't seem to find that tag.

**Comment by dbouwman** [comment] 2015-02-19 23:25
There definitely is a 0.1.8 listed on npm 
![image](https://cloud.githubusercontent.com/assets/119129/6278393/bf9a0612-b853-11e4-9d0d-bbd858b8e96e.png)

And I can confirm the same behavior. Switching back to 0.1.7 fixed this

**Comment by jonathanepollack** [comment] 2015-02-20 06:17
Crap. Alright, let me roll a fix for this later today.

**Comment by jonathanepollack** [comment] 2015-02-20 11:01
So it appears that the latest version of Minimize intentionally did this by making all HTML commented data equivalent (https://github.com/Moveo/minimize/blob/master/lib/helpers.js#L253). Put in an issue with this, and see if they'll move back to making a distinction between HTML comments and HTML conditionals.

For the time being, I'm actually going to clean up the dependencies, and move this package over to proper SEMVER. So we're going to push this to v.1.0.0

**Comment by dbouwman** [comment] 2015-02-20 15:27
Thanks @jonathanepollack - appreciate you digging into this, and replying so quickly :)

**Comment by jonathanepollack** [comment] 2015-02-20 15:47
No prob. Time to take it up with the `Minimize` boys.

**Closed by jonathanepollack** 2015-02-20 15:47 UTC

**Comment by jonathanepollack** [comment] 2015-03-09 14:39
Fixed in https://github.com/Moveo/minimize/issues/34
